"""Biblioteka ćwiczeń trenera V2 — dane źródłowe importu do bazy ćwiczeń.

PROWENIENCJA. Dane pochodzą z arkusza „Ćwiczenia V2 PL” w pliku
`DZIK_OS_Biblioteka_Cwiczen_V2_PL_120.xlsx`, przekazanym przez trenera
2026-08-18 (120 wierszy, 19 kolumn). Plik źródłowy jest binarny i NIE jest
commitowany — ten moduł jest jego czytelną, diffowalną postacią, dokładnie
tak jak `food_catalog_data.py` dla katalogu produktów. Każda pozycja
zaimportowana do bazy dostaje `source_kind="IMPORTED"` i `source_ref`
wskazujący tę bibliotekę wraz z datą, żeby dało się ją odróżnić od
ćwiczenia opisanego ręcznie przez trenera.

CO W ŹRÓDLE JEST WARTOŚCIOWE, A CO SZABLONOWE — to rozróżnienie jest
powodem, dla którego moduł wygląda tak, a nie inaczej:

* Kolumny **faktograficzne są unikalne dla każdego ćwiczenia**: nazwa
  polska i angielska, kategoria, mięśnie główne i pomocnicze, sprzęt,
  poziom, rodzaj ćwiczenia, wzorzec ruchowy, tagi. To one mają wartość i
  to one trafiają do bazy jako dane pozycji.
* Kolumny **opisowe są szablonowe**: 120 wierszy ma tylko 17 różnych
  opisów wykonania, 2 opisy oddychania, 5 zestawów najczęstszych błędów,
  12 opisów zastosowania, 8 regresji i 4 progresje. Opis techniki jest
  więc ogólny dla wzorca ruchu, a nie napisany pod konkretne ćwiczenie.

Dlatego teksty opisowe leżą tu jako NAZWANE STAŁE, do których wiersze się
odwołują kluczem: szablonowość ma być widoczna w kodzie, a nie ukryta w
120 powtórzeniach tego samego akapitu. Z tego samego powodu import
oznacza każdą NOWO UTWORZONĄ pozycję notatką „opis ogólny” (`review_reason`)
— to informacja robocza dla trenera, co jeszcze warto opisać po swojemu,
a nie ocena jakości ćwiczenia pokazywana klientowi.

ZAKRES ODPOWIEDZIALNOŚCI (Human OS): to know-how treningowe, nie porada
medyczna. Moduł niczego nie ocenia i nie dobiera — dostarcza materiał, z
którego wybiera trener.

Mapowanie na słowniki `muscles.py` (kategoria → grupa, wzorzec źródłowy →
wzorzec ruchu, tekst anatomiczny → klucz partii mięśniowej) NIE jest
częścią tego modułu — mieszka w `import_exercises.py` razem z raportem
wartości nierozpoznanych. Tutaj są wyłącznie dane w postaci źródłowej.
"""

from __future__ import annotations

from typing import NamedTuple

#: Nazwa biblioteki widoczna w proweniencji wpisu.
LIBRARY_NAME = "Biblioteka ćwiczeń trenera V2"

#: Nazwa pliku źródłowego (do repo NIE trafia — patrz nagłówek modułu).
LIBRARY_SOURCE_FILE = "DZIK_OS_Biblioteka_Cwiczen_V2_PL_120.xlsx"

#: Data przekazania pliku przez trenera.
LIBRARY_RECEIVED = "2026-08-18"

#: Wpisywane w kolumnę `exercises.source_ref` — biblioteka + data.
LIBRARY_REF = f"{LIBRARY_NAME} ({LIBRARY_RECEIVED})"

#: Notatka robocza dla trenera na nowo utworzonych pozycjach. Widoczna
#: WYŁĄCZNIE w panelu trenera; klient nigdy jej nie dostaje (opis w
#: `routers/exercises.py::_out`).
GENERIC_DESCRIPTION_NOTE = (
    "Opis techniki, oddychania i błędów pochodzi z szablonu biblioteki V2 "
    "(wspólny dla całego wzorca ruchu) — warto opisać to ćwiczenie własnymi "
    "słowami."
)


class LibraryRow(NamedTuple):
    """Jeden wiersz arkusza w postaci źródłowej — bez mapowania.

    Pola `benefit`, `steps`, `breathing`, `mistakes`, `easier`, `harder` to
    KLUCZE do szablonów niżej, nie teksty: w źródle te kolumny powtarzają
    się dziesiątki razy.

    Kolumny „Film instruktażowy” i „Zdjęcie / GIF” są w źródle puste dla
    wszystkich 120 wierszy — świadomie nie ma ich w tej strukturze.
    """

    id: str
    name_pl: str
    name_en: str
    category: str
    primary: tuple[str, ...]
    secondary: tuple[str, ...]
    equipment: tuple[str, ...]
    level: str
    kind: str
    pattern: str
    tags: tuple[str, ...]
    benefit: str
    steps: str
    breathing: str
    mistakes: str
    easier: str
    harder: str

#: Wykonanie krok po kroku — 17 szablonów na 120 wierszy źródła.
STEP_TEXTS: dict[str, tuple[str, ...]] = {
    "wypychanie": (
        "Ustaw stabilnie tułów i obręcz barkową.",
        (
            "Rozpocznij z kontrolowanej pozycji, wypchnij ciężar bez "
            "szarpania i bez utraty ustawienia stawów."
        ),
        (
            "Wróć powoli do pozycji początkowej, zachowując napięcie "
            "mięśni."
        ),
    ),
    "staw_ramienny": (
        "Ustaw tułów stabilnie i rozpocznij ruch w stawie ramiennym.",
        (
            "Prowadź kończynę płynnie w kontrolowanym zakresie, bez zamachu "
            "i bez unoszenia barków."
        ),
        "Powrót wykonaj wolniej niż fazę unoszenia/przyciągania.",
    ),
    "przyciaganie_pionowe": (
        "Ustabilizuj tułów i łopatki.",
        (
            "Przyciągaj poprzez prowadzenie łokci w dół, bez kołysania "
            "ciałem."
        ),
        (
            "Zakończ ruch w zakresie, w którym barki pozostają pod "
            "kontrolą, po czym powoli wróć do wyprostu."
        ),
    ),
    "przyciaganie_poziome": (
        "Ustabilizuj tułów.",
        (
            "Przyciągnij obciążenie w stronę tułowia, prowadząc łokcie do "
            "tyłu i kontrolując ruch łopatek."
        ),
        "Nie odchylaj gwałtownie tułowia.",
        "Powoli wyprostuj ramiona.",
    ),
    "ogolny": (
        (
            "Przyjmij stabilną pozycję wyjściową, napnij tułów i wykonuj "
            "ruch płynnie w komfortowym zakresie."
        ),
        (
            "Faza powrotna powinna być kontrolowana; nie używaj zamachu ani "
            "ciężaru, który wymusza utratę techniki."
        ),
    ),
    "zgiecie_lokcia": (
        "Ustaw łokcie stabilnie i napnij tułów.",
        (
            "Zegnij łokcie bez zarzucania ciężaru i bez nadmiernego "
            "przesuwania ramion."
        ),
        (
            "W górze zachowaj napięcie, następnie kontrolowanie opuść "
            "ciężar do pełnego, komfortowego zakresu."
        ),
    ),
    "wyprost_lokcia": (
        "Ustabilizuj ramiona i tułów.",
        "Wyprostuj łokcie przeciwko oporowi bez ruchu barkami.",
        (
            "Zatrzymaj na moment w końcowej pozycji, następnie powoli wróć "
            "do zgięcia łokci."
        ),
    ),
    "przysiad": (
        "Ustaw stopy stabilnie i napnij tułów.",
        (
            "Zginaj biodra i kolana w kontrolowanym tempie, prowadząc "
            "kolana zgodnie z kierunkiem stóp."
        ),
        (
            "Zejdź tylko tak głęboko, jak pozwala zachowanie stabilnej "
            "pozycji, następnie odepchnij podłoże i wróć do pozycji "
            "wyjściowej."
        ),
    ),
    "wyprost_kolana": (
        "Ustaw kolano zgodnie z osią maszyny i oprzyj plecy.",
        (
            "Wyprostuj nogę w kontrolowany sposób, bez gwałtownego "
            "blokowania stawu."
        ),
        "Zatrzymaj na moment i powoli wróć.",
    ),
    "jednonoz": (
        "Ustaw stopę nogi pracującej stabilnie.",
        (
            "Obniż ciało lub wejdź na podwyższenie, kontrolując ustawienie "
            "kolana i miednicy."
        ),
        (
            "Odepchnij się głównie nogą pracującą i wróć bez utraty "
            "równowagi."
        ),
    ),
    "zawias": (
        "Ustaw stopy stabilnie, lekko ugnij kolana i napnij brzuch.",
        (
            "Cofaj biodra, utrzymując kręgosłup w neutralnej pozycji i "
            "ciężar blisko ciała."
        ),
        (
            "Zatrzymaj ruch przed utratą ustawienia tułowia, następnie "
            "wyprostuj biodra przez napięcie pośladków."
        ),
    ),
    "zgiecie_kolana": (
        (
            "Ustaw staw kolanowy zgodnie z osią urządzenia lub przyjmij "
            "stabilną pozycję."
        ),
        (
            "Zegnij kolano przeciwko oporowi, nie odrywając bioder i nie "
            "szarpiąc."
        ),
        "Powoli wróć do prawie pełnego wyprostu.",
    ),
    "wyprost_biodra": (
        "Ustabilizuj miednicę i tułów.",
        (
            "Wyprostuj biodro przez napięcie pośladków, unikając przeprostu "
            "odcinka lędźwiowego."
        ),
        "Zatrzymaj na moment i wróć pod kontrolą.",
    ),
    "wspiecie": (
        "Ustaw śródstopie stabilnie na podparciu.",
        (
            "Opuść piętę w komfortowym zakresie, następnie wykonaj pełne "
            "wspięcie na palce."
        ),
        "Zatrzymaj ruch w górze i wróć powoli bez odbijania.",
    ),
    "zgiecie_grzbietowe": (
        "Utrzymuj pięty stabilnie.",
        (
            "Unieś przodostopie i palce w kierunku goleni, napinając "
            "przednią część podudzia."
        ),
        "Zatrzymaj na moment i kontrolowanie opuść.",
    ),
    "stabilizacja": (
        (
            "Ustaw kręgosłup i miednicę neutralnie, napnij brzuch i "
            "pośladki."
        ),
        (
            "Utrzymuj pozycję lub wykonuj ruch kończynami bez utraty "
            "ustawienia tułowia."
        ),
        "Przerwij serię, gdy zaczynasz kompensować ruchem kręgosłupa.",
    ),
    "chwyt": (
        (
            "Chwyć obciążenie pewnie, ustaw nadgarstki neutralnie i "
            "ustabilizuj barki."
        ),
        "Utrzymuj mocny chwyt przez cały czas, bez zapadania sylwetki.",
        (
            "W ćwiczeniach marszowych poruszaj się krótkimi, kontrolowanymi "
            "krokami."
        ),
    ),
}

#: Oddychanie — 2 szablony na 120 wierszy źródła.
BREATHING_TEXTS: dict[str, str] = {
    "napiecie": (
        "Przed trudną fazą ruchu weź wdech i usztywnij tułów; wypuszczaj "
        "powietrze po przejściu najtrudniejszego fragmentu. Przy większych "
        "ciężarach utrzymuj napięcie oddechowe zgodnie z doświadczeniem i "
        "zaleceniami trenera."
    ),
    "plynnie": (
        "Oddychaj płynnie. Zwykle wykonuj wydech podczas fazy pokonywania "
        "oporu, a wdech podczas kontrolowanego powrotu."
    ),
}

#: Najczęstsze błędy — 5 szablonów na 120 wierszy źródła.
MISTAKE_TEXTS: dict[str, tuple[str, ...]] = {
    "wypychanie": (
        "utrata stabilizacji barków",
        "zbyt duży ciężar",
        "gwałtowne blokowanie stawów",
        "odbijanie lub szarpanie",
    ),
    "ogolne": (
        "zbyt duży ciężar",
        "wykonywanie ruchu z rozpędu",
        "skracanie zakresu kosztem techniki",
    ),
    "przyciaganie": (
        "kołysanie tułowiem",
        "ciągnięcie głównie dłońmi",
        "unoszenie barków",
        "brak kontroli fazy powrotnej",
    ),
    "nogi": (
        "zapadanie kolan do środka",
        "odrywanie stopy od podłoża",
        "utrata stabilności tułowia",
        "zbyt duży ciężar",
    ),
    "zawias": (
        "zaokrąglanie pleców",
        "zamiana ruchu biodra w przysiad",
        "odsuwanie ciężaru od nóg",
        "przeprost w końcowej fazie",
    ),
}

#: Największy wpływ / zastosowanie — 12 szablonów (po jednym na kategorię).
BENEFIT_TEXTS: dict[str, str] = {
    "klatka": (
        "Rozwój siły i masy klatki piersiowej oraz sprawności w ruchach "
        "wypychających."
    ),
    "najszerszy": (
        "Rozwój mięśnia najszerszego grzbietu, siły przyciągania i "
        "wizualnej szerokości pleców."
    ),
    "gora_plecow": (
        "Rozwój grubości górnej części pleców, kontroli łopatek i siły "
        "przyciągania."
    ),
    "barki": "Rozwój siły, masy i stabilności obręczy barkowej.",
    "biceps": "Rozwój zginaczy łokcia, masy ramienia i siły przyciągania.",
    "triceps": (
        "Rozwój prostowników łokcia, masy tylnej części ramienia i siły "
        "wypychania."
    ),
    "czworoglowy": (
        "Rozwój siły i masy przedniej części uda oraz zdolności prostowania "
        "kolana."
    ),
    "kulszowo_goleniowe": (
        "Rozwój mięśni kulszowo-goleniowych, siły tylnego łańcucha i "
        "kontroli biodra/kolana."
    ),
    "posladki": (
        "Rozwój siły wyprostu i stabilizacji biodra oraz masy mięśni "
        "pośladkowych."
    ),
    "podudzie": "Rozwój mięśni podudzia, siły stawu skokowego i kontroli stopy.",
    "tulow": (
        "Rozwój kontroli tułowia, stabilizacji kręgosłupa i przenoszenia "
        "siły między kończynami."
    ),
    "chwyt": (
        "Rozwój siły chwytu, wytrzymałości przedramion i kontroli "
        "nadgarstka."
    ),
}

#: Wariant łatwiejszy — 8 szablonów na 120 wierszy źródła.
EASIER_TEXTS: dict[str, str] = {
    "maszyna": "analogiczne ćwiczenie na maszynie lub z mniejszym obciążeniem",
    "pompki": "pompki na wyższym podparciu lub krótszy zakres ruchu",
    "ogolna": (
        "mniejsze obciążenie, krótszy zakres lub bardziej stabilna wersja "
        "ćwiczenia"
    ),
    "wspomaganie": (
        "wersja ze wspomaganiem gumą lub maszyną / ściąganie wyciągu "
        "górnego"
    ),
    "maszyna_wyciag": "analogiczne ćwiczenie na maszynie/wyciągu z mniejszym obciążeniem",
    "przysiad": "przysiad bez obciążenia lub z hantlem przed klatką",
    "zawias": "nauka zawiasu biodrowego z lekkim hantlem lub kijem",
    "dzwignia": "krótsza dźwignia, krótszy czas utrzymania lub łatwiejsza pozycja",
}

#: Wariant trudniejszy — 4 szablony na 120 wierszy źródła.
HARDER_TEXTS: dict[str, str] = {
    "obciazenie_pauza": (
        "stopniowe zwiększenie obciążenia, pauza w trudnej pozycji lub "
        "wolniejsza faza ekscentryczna"
    ),
    "zakres": "większy zakres ruchu, dodatkowe obciążenie lub trudniejsza pozycja",
    "ogolna": "większe obciążenie, dłuższy czas napięcia lub trudniejszy wariant",
    "pauza": "dodatkowe obciążenie, pauza lub wolniejsza faza opuszczania",
}

LIBRARY_ROWS: list[LibraryRow] = [
    # --- Klatka piersiowa ---
    LibraryRow(
        "EX-KLATKA-001", "Wyciskanie sztangi na ławce poziomej",
        "Barbell Bench Press",
        "Klatka piersiowa",
        primary=("mięsień piersiowy większy",),
        secondary=("triceps", "przednia część mięśnia naramiennego"),
        equipment=("sztanga", "ławka", "stojaki"),
        level="średniozaawansowany", kind="wielostawowe",
        pattern="wypychanie poziome",
        tags=("klatka piersiowa", "wypychanie poziome", "wielostawowe"),
        benefit="klatka", steps="wypychanie",
        breathing="napiecie", mistakes="wypychanie",
        easier="maszyna", harder="obciazenie_pauza",
    ),
    LibraryRow(
        "EX-KLATKA-002", "Wyciskanie hantli na ławce poziomej",
        "Dumbbell Bench Press",
        "Klatka piersiowa",
        primary=("mięsień piersiowy większy",),
        secondary=("triceps", "przednia część mięśnia naramiennego"),
        equipment=("hantle", "ławka"),
        level="początkujący/średniozaawansowany", kind="wielostawowe",
        pattern="wypychanie poziome",
        tags=("klatka piersiowa", "wypychanie poziome", "wielostawowe"),
        benefit="klatka", steps="wypychanie",
        breathing="napiecie", mistakes="wypychanie",
        easier="maszyna", harder="obciazenie_pauza",
    ),
    LibraryRow(
        "EX-KLATKA-003", "Wyciskanie hantli na ławce skośnej dodatniej",
        "Incline Dumbbell Press",
        "Klatka piersiowa",
        primary=("górna część mięśnia piersiowego większego",),
        secondary=("triceps", "przednia część mięśnia naramiennego"),
        equipment=("hantle", "ławka regulowana"),
        level="początkujący/średniozaawansowany", kind="wielostawowe",
        pattern="wypychanie skośne",
        tags=("klatka piersiowa", "wypychanie skośne", "wielostawowe"),
        benefit="klatka", steps="wypychanie",
        breathing="napiecie", mistakes="wypychanie",
        easier="maszyna", harder="obciazenie_pauza",
    ),
    LibraryRow(
        "EX-KLATKA-004", "Wyciskanie sztangi na ławce skośnej dodatniej",
        "Incline Barbell Bench Press",
        "Klatka piersiowa",
        primary=("górna część mięśnia piersiowego większego",),
        secondary=("triceps", "przednia część mięśnia naramiennego"),
        equipment=("sztanga", "ławka regulowana", "stojaki"),
        level="średniozaawansowany", kind="wielostawowe",
        pattern="wypychanie skośne",
        tags=("klatka piersiowa", "wypychanie skośne", "wielostawowe"),
        benefit="klatka", steps="wypychanie",
        breathing="napiecie", mistakes="wypychanie",
        easier="maszyna", harder="obciazenie_pauza",
    ),
    LibraryRow(
        "EX-KLATKA-005", "Wyciskanie na maszynie siedząc",
        "Machine Chest Press",
        "Klatka piersiowa",
        primary=("mięsień piersiowy większy",),
        secondary=("triceps", "przednia część mięśnia naramiennego"),
        equipment=("maszyna",),
        level="początkujący", kind="wielostawowe",
        pattern="wypychanie poziome",
        tags=("klatka piersiowa", "wypychanie poziome", "wielostawowe"),
        benefit="klatka", steps="wypychanie",
        breathing="napiecie", mistakes="wypychanie",
        easier="maszyna", harder="obciazenie_pauza",
    ),
    LibraryRow(
        "EX-KLATKA-006", "Pompki klasyczne",
        "Push-Up",
        "Klatka piersiowa",
        primary=("mięsień piersiowy większy",),
        secondary=("triceps", "przednia część barków", "mięśnie głębokie tułowia"),
        equipment=("masa własnego ciała",),
        level="początkujący", kind="wielostawowe",
        pattern="wypychanie poziome",
        tags=("klatka piersiowa", "wypychanie poziome", "wielostawowe"),
        benefit="klatka", steps="wypychanie",
        breathing="napiecie", mistakes="wypychanie",
        easier="pompki", harder="zakres",
    ),
    LibraryRow(
        "EX-KLATKA-007", "Pompki na podwyższeniu",
        "Incline Push-Up",
        "Klatka piersiowa",
        primary=("mięsień piersiowy większy",),
        secondary=("triceps", "barki", "mięśnie głębokie tułowia"),
        equipment=("ławka/podwyższenie", "masa własnego ciała"),
        level="początkujący", kind="wielostawowe",
        pattern="wypychanie poziome",
        tags=("klatka piersiowa", "wypychanie poziome", "wielostawowe"),
        benefit="klatka", steps="wypychanie",
        breathing="napiecie", mistakes="wypychanie",
        easier="pompki", harder="zakres",
    ),
    LibraryRow(
        "EX-KLATKA-008", "Pompki z deficytu",
        "Deficit Push-Up",
        "Klatka piersiowa",
        primary=("mięsień piersiowy większy",),
        secondary=("triceps", "przednia część barków", "core"),
        equipment=("uchwyty/podwyższenia", "masa własnego ciała"),
        level="średniozaawansowany", kind="wielostawowe",
        pattern="wypychanie poziome",
        tags=("klatka piersiowa", "wypychanie poziome", "wielostawowe"),
        benefit="klatka", steps="wypychanie",
        breathing="napiecie", mistakes="wypychanie",
        easier="pompki", harder="zakres",
    ),
    LibraryRow(
        "EX-KLATKA-009", "Rozpiętki na bramie",
        "Cable Fly",
        "Klatka piersiowa",
        primary=("mięsień piersiowy większy",),
        secondary=("przednia część barków",),
        equipment=("brama/wyciąg",),
        level="początkujący", kind="izolowane",
        pattern="przywodzenie ramienia",
        tags=("klatka piersiowa", "przywodzenie ramienia", "izolowane"),
        benefit="klatka", steps="staw_ramienny",
        breathing="plynnie", mistakes="ogolne",
        easier="ogolna", harder="ogolna",
    ),
    LibraryRow(
        "EX-KLATKA-010", "Rozpiętki na maszynie",
        "Pec Deck Fly",
        "Klatka piersiowa",
        primary=("mięsień piersiowy większy",),
        secondary=("przednia część barków",),
        equipment=("maszyna pec deck",),
        level="początkujący", kind="izolowane",
        pattern="przywodzenie ramienia",
        tags=("klatka piersiowa", "przywodzenie ramienia", "izolowane"),
        benefit="klatka", steps="staw_ramienny",
        breathing="plynnie", mistakes="ogolne",
        easier="ogolna", harder="ogolna",
    ),
    # --- Plecy — najszerszy grzbietu ---
    LibraryRow(
        "EX-LAT-001", "Podciąganie na drążku nachwytem",
        "Pull-Up",
        "Plecy — najszerszy grzbietu",
        primary=("mięsień najszerszy grzbietu",),
        secondary=("biceps", "mięsień ramienny", "obły większy", "mięśnie łopatki"),
        equipment=("drążek",),
        level="średniozaawansowany", kind="wielostawowe",
        pattern="przyciąganie pionowe",
        tags=("plecy — najszerszy grzbietu", "przyciąganie pionowe", "wielostawowe"),
        benefit="najszerszy", steps="przyciaganie_pionowe",
        breathing="napiecie", mistakes="przyciaganie",
        easier="wspomaganie", harder="pauza",
    ),
    LibraryRow(
        "EX-LAT-002", "Podciąganie na drążku podchwytem",
        "Chin-Up",
        "Plecy — najszerszy grzbietu",
        primary=("mięsień najszerszy grzbietu",),
        secondary=("biceps", "mięsień ramienny", "obły większy"),
        equipment=("drążek",),
        level="średniozaawansowany", kind="wielostawowe",
        pattern="przyciąganie pionowe",
        tags=("plecy — najszerszy grzbietu", "przyciąganie pionowe", "wielostawowe"),
        benefit="najszerszy", steps="przyciaganie_pionowe",
        breathing="napiecie", mistakes="przyciaganie",
        easier="wspomaganie", harder="pauza",
    ),
    LibraryRow(
        "EX-LAT-003", "Podciąganie chwytem neutralnym",
        "Neutral-Grip Pull-Up",
        "Plecy — najszerszy grzbietu",
        primary=("mięsień najszerszy grzbietu",),
        secondary=("biceps", "mięsień ramienny", "obły większy"),
        equipment=("drążek z uchwytami neutralnymi",),
        level="średniozaawansowany", kind="wielostawowe",
        pattern="przyciąganie pionowe",
        tags=("plecy — najszerszy grzbietu", "przyciąganie pionowe", "wielostawowe"),
        benefit="najszerszy", steps="przyciaganie_pionowe",
        breathing="napiecie", mistakes="przyciaganie",
        easier="wspomaganie", harder="pauza",
    ),
    LibraryRow(
        "EX-LAT-004", "Ściąganie drążka wyciągu górnego do klatki",
        "Lat Pulldown",
        "Plecy — najszerszy grzbietu",
        primary=("mięsień najszerszy grzbietu",),
        secondary=("biceps", "obły większy", "mięśnie łopatki"),
        equipment=("wyciąg górny",),
        level="początkujący", kind="wielostawowe",
        pattern="przyciąganie pionowe",
        tags=("plecy — najszerszy grzbietu", "przyciąganie pionowe", "wielostawowe"),
        benefit="najszerszy", steps="przyciaganie_pionowe",
        breathing="napiecie", mistakes="przyciaganie",
        easier="maszyna_wyciag", harder="obciazenie_pauza",
    ),
    LibraryRow(
        "EX-LAT-005", "Ściąganie uchwytu neutralnego wyciągu górnego",
        "Neutral-Grip Lat Pulldown",
        "Plecy — najszerszy grzbietu",
        primary=("mięsień najszerszy grzbietu",),
        secondary=("biceps", "mięsień ramienny", "obły większy"),
        equipment=("wyciąg górny", "uchwyt neutralny"),
        level="początkujący", kind="wielostawowe",
        pattern="przyciąganie pionowe",
        tags=("plecy — najszerszy grzbietu", "przyciąganie pionowe", "wielostawowe"),
        benefit="najszerszy", steps="przyciaganie_pionowe",
        breathing="napiecie", mistakes="przyciaganie",
        easier="maszyna_wyciag", harder="obciazenie_pauza",
    ),
    LibraryRow(
        "EX-LAT-006", "Ściąganie wyciągu górnego jednorącz",
        "Single-Arm Lat Pulldown",
        "Plecy — najszerszy grzbietu",
        primary=("mięsień najszerszy grzbietu",),
        secondary=("biceps", "obły większy"),
        equipment=("wyciąg górny", "pojedynczy uchwyt"),
        level="początkujący/średniozaawansowany", kind="wielostawowe",
        pattern="przyciąganie pionowe",
        tags=("plecy — najszerszy grzbietu", "przyciąganie pionowe", "wielostawowe"),
        benefit="najszerszy", steps="przyciaganie_pionowe",
        breathing="napiecie", mistakes="przyciaganie",
        easier="maszyna_wyciag", harder="obciazenie_pauza",
    ),
    LibraryRow(
        "EX-LAT-007", "Ściąganie prostych ramion na wyciągu",
        "Straight-Arm Pulldown",
        "Plecy — najszerszy grzbietu",
        primary=("mięsień najszerszy grzbietu",),
        secondary=("obły większy", "głowa długa tricepsa"),
        equipment=("wyciąg górny", "drążek/lina"),
        level="początkujący", kind="izolowane",
        pattern="wyprost ramienia",
        tags=("plecy — najszerszy grzbietu", "wyprost ramienia", "izolowane"),
        benefit="najszerszy", steps="staw_ramienny",
        breathing="plynnie", mistakes="ogolne",
        easier="ogolna", harder="ogolna",
    ),
    LibraryRow(
        "EX-LAT-008", "Pullover na wyciągu klęcząc",
        "Kneeling Cable Pullover",
        "Plecy — najszerszy grzbietu",
        primary=("mięsień najszerszy grzbietu",),
        secondary=("obły większy", "mięśnie brzucha stabilizacyjnie"),
        equipment=("wyciąg górny", "lina"),
        level="średniozaawansowany", kind="izolowane",
        pattern="wyprost ramienia",
        tags=("plecy — najszerszy grzbietu", "wyprost ramienia", "izolowane"),
        benefit="najszerszy", steps="staw_ramienny",
        breathing="plynnie", mistakes="ogolne",
        easier="ogolna", harder="ogolna",
    ),
    LibraryRow(
        "EX-LAT-009", "Pullover hantlem leżąc",
        "Dumbbell Pullover",
        "Plecy — najszerszy grzbietu",
        primary=("mięsień najszerszy grzbietu", "mięśnie piersiowe"),
        secondary=("triceps", "zębaty przedni"),
        equipment=("hantel", "ławka"),
        level="średniozaawansowany", kind="wielostawowe",
        pattern="wyprost/zgięcie ramienia",
        tags=("plecy — najszerszy grzbietu", "wyprost/zgięcie ramienia", "wielostawowe"),
        benefit="najszerszy", steps="staw_ramienny",
        breathing="plynnie", mistakes="ogolne",
        easier="ogolna", harder="ogolna",
    ),
    LibraryRow(
        "EX-LAT-010", "Ściąganie drążka półklęcząc jednorącz",
        "Half-Kneeling Single-Arm Pulldown",
        "Plecy — najszerszy grzbietu",
        primary=("mięsień najszerszy grzbietu",),
        secondary=("biceps", "obły większy", "core"),
        equipment=("wyciąg górny",),
        level="średniozaawansowany", kind="wielostawowe",
        pattern="przyciąganie pionowe",
        tags=("plecy — najszerszy grzbietu", "przyciąganie pionowe", "wielostawowe"),
        benefit="najszerszy", steps="przyciaganie_pionowe",
        breathing="napiecie", mistakes="przyciaganie",
        easier="maszyna_wyciag", harder="obciazenie_pauza",
    ),
    # --- Plecy — środek i góra ---
    LibraryRow(
        "EX-PLECY-001", "Wiosłowanie sztangą w opadzie",
        "Barbell Bent-Over Row",
        "Plecy — środek i góra",
        primary=("mięśnie środkowej części grzbietu", "najszerszy grzbietu"),
        secondary=("biceps", "tylny bark", "prostowniki grzbietu"),
        equipment=("sztanga",),
        level="średniozaawansowany", kind="wielostawowe",
        pattern="przyciąganie poziome",
        tags=("plecy — środek i góra", "przyciąganie poziome", "wielostawowe"),
        benefit="gora_plecow", steps="przyciaganie_poziome",
        breathing="napiecie", mistakes="przyciaganie",
        easier="maszyna_wyciag", harder="obciazenie_pauza",
    ),
    LibraryRow(
        "EX-PLECY-002", "Wiosłowanie hantlem jednorącz",
        "One-Arm Dumbbell Row",
        "Plecy — środek i góra",
        primary=("mięsień najszerszy grzbietu", "mięśnie międzyłopatkowe"),
        secondary=("biceps", "tylny bark"),
        equipment=("hantel", "ławka"),
        level="początkujący/średniozaawansowany", kind="wielostawowe",
        pattern="przyciąganie poziome",
        tags=("plecy — środek i góra", "przyciąganie poziome", "wielostawowe"),
        benefit="gora_plecow", steps="przyciaganie_poziome",
        breathing="napiecie", mistakes="przyciaganie",
        easier="maszyna_wyciag", harder="obciazenie_pauza",
    ),
    LibraryRow(
        "EX-PLECY-003", "Wiosłowanie na wyciągu siedząc",
        "Seated Cable Row",
        "Plecy — środek i góra",
        primary=("mięśnie środkowej części grzbietu",),
        secondary=("najszerszy grzbietu", "biceps", "tylny bark"),
        equipment=("wyciąg dolny",),
        level="początkujący", kind="wielostawowe",
        pattern="przyciąganie poziome",
        tags=("plecy — środek i góra", "przyciąganie poziome", "wielostawowe"),
        benefit="gora_plecow", steps="przyciaganie_poziome",
        breathing="napiecie", mistakes="przyciaganie",
        easier="maszyna_wyciag", harder="obciazenie_pauza",
    ),
    LibraryRow(
        "EX-PLECY-004", "Wiosłowanie na maszynie z podparciem klatki",
        "Chest-Supported Machine Row",
        "Plecy — środek i góra",
        primary=("mięśnie środkowej i górnej części grzbietu",),
        secondary=("najszerszy grzbietu", "biceps", "tylny bark"),
        equipment=("maszyna",),
        level="początkujący", kind="wielostawowe",
        pattern="przyciąganie poziome",
        tags=("plecy — środek i góra", "przyciąganie poziome", "wielostawowe"),
        benefit="gora_plecow", steps="przyciaganie_poziome",
        breathing="napiecie", mistakes="przyciaganie",
        easier="maszyna_wyciag", harder="obciazenie_pauza",
    ),
    LibraryRow(
        "EX-PLECY-005", "Wiosłowanie hantlami z klatką opartą o ławkę",
        "Chest-Supported Dumbbell Row",
        "Plecy — środek i góra",
        primary=("mięśnie międzyłopatkowe",),
        secondary=("najszerszy grzbietu", "biceps", "tylny bark"),
        equipment=("hantle", "ławka skośna"),
        level="początkujący/średniozaawansowany", kind="wielostawowe",
        pattern="przyciąganie poziome",
        tags=("plecy — środek i góra", "przyciąganie poziome", "wielostawowe"),
        benefit="gora_plecow", steps="przyciaganie_poziome",
        breathing="napiecie", mistakes="przyciaganie",
        easier="maszyna_wyciag", harder="obciazenie_pauza",
    ),
    LibraryRow(
        "EX-PLECY-006", "Wiosłowanie sztangą typu T",
        "T-Bar Row",
        "Plecy — środek i góra",
        primary=("mięśnie środkowej części grzbietu",),
        secondary=("najszerszy grzbietu", "biceps", "tylny bark"),
        equipment=("sztanga T/landmine",),
        level="średniozaawansowany", kind="wielostawowe",
        pattern="przyciąganie poziome",
        tags=("plecy — środek i góra", "przyciąganie poziome", "wielostawowe"),
        benefit="gora_plecow", steps="przyciaganie_poziome",
        breathing="napiecie", mistakes="przyciaganie",
        easier="maszyna_wyciag", harder="obciazenie_pauza",
    ),
    LibraryRow(
        "EX-PLECY-007", "Przyciąganie liny do twarzy",
        "Face Pull",
        "Plecy — środek i góra",
        primary=("tylna część barków", "mięsień czworoboczny środkowy i dolny"),
        secondary=("równoległoboczne", "rotatory zewnętrzne barku"),
        equipment=("wyciąg", "lina"),
        level="początkujący", kind="wielostawowe",
        pattern="przyciąganie poziome/rotacja zewnętrzna",
        tags=("plecy — środek i góra", "przyciąganie poziome/rotacja zewnętrzna", "wielostawowe"),
        benefit="gora_plecow", steps="przyciaganie_poziome",
        breathing="napiecie", mistakes="przyciaganie",
        easier="maszyna_wyciag", harder="obciazenie_pauza",
    ),
    LibraryRow(
        "EX-PLECY-008", "Odwrotne rozpiętki na maszynie",
        "Reverse Pec Deck",
        "Plecy — środek i góra",
        primary=("tylna część mięśnia naramiennego",),
        secondary=("równoległoboczne", "środkowy mięsień czworoboczny"),
        equipment=("maszyna pec deck",),
        level="początkujący", kind="izolowane",
        pattern="odwodzenie poziome ramienia",
        tags=("plecy — środek i góra", "odwodzenie poziome ramienia", "izolowane"),
        benefit="gora_plecow", steps="staw_ramienny",
        breathing="plynnie", mistakes="ogolne",
        easier="ogolna", harder="ogolna",
    ),
    LibraryRow(
        "EX-PLECY-009", "Unoszenie ramion w kształcie Y na ławce",
        "Incline Y Raise",
        "Plecy — środek i góra",
        primary=("dolna część mięśnia czworobocznego",),
        secondary=("tylny bark", "mięśnie stożka rotatorów"),
        equipment=("lekkie hantle", "ławka"),
        level="początkujący/średniozaawansowany", kind="izolowane",
        pattern="unoszenie ramion w płaszczyźnie łopatki",
        tags=("plecy — środek i góra", "unoszenie ramion w płaszczyźnie łopatki", "izolowane"),
        benefit="gora_plecow", steps="ogolny",
        breathing="plynnie", mistakes="ogolne",
        easier="ogolna", harder="ogolna",
    ),
    LibraryRow(
        "EX-PLECY-010", "Szrugsy z hantlami",
        "Dumbbell Shrug",
        "Plecy — środek i góra",
        primary=("górna część mięśnia czworobocznego",),
        secondary=("dźwigacz łopatki", "przedramiona"),
        equipment=("hantle",),
        level="początkujący", kind="izolowane",
        pattern="unoszenie łopatki",
        tags=("plecy — środek i góra", "unoszenie łopatki", "izolowane"),
        benefit="gora_plecow", steps="ogolny",
        breathing="plynnie", mistakes="ogolne",
        easier="ogolna", harder="ogolna",
    ),
    # --- Barki ---
    LibraryRow(
        "EX-BARKI-001", "Wyciskanie sztangi nad głowę stojąc",
        "Barbell Overhead Press",
        "Barki",
        primary=("mięsień naramienny — część przednia i boczna",),
        secondary=("triceps", "górna część klatki", "core"),
        equipment=("sztanga", "stojaki"),
        level="średniozaawansowany", kind="wielostawowe",
        pattern="wypychanie pionowe",
        tags=("barki", "wypychanie pionowe", "wielostawowe"),
        benefit="barki", steps="wypychanie",
        breathing="napiecie", mistakes="wypychanie",
        easier="maszyna", harder="obciazenie_pauza",
    ),
    LibraryRow(
        "EX-BARKI-002", "Wyciskanie hantli nad głowę siedząc",
        "Seated Dumbbell Shoulder Press",
        "Barki",
        primary=("mięsień naramienny — część przednia i boczna",),
        secondary=("triceps",),
        equipment=("hantle", "ławka"),
        level="początkujący/średniozaawansowany", kind="wielostawowe",
        pattern="wypychanie pionowe",
        tags=("barki", "wypychanie pionowe", "wielostawowe"),
        benefit="barki", steps="wypychanie",
        breathing="napiecie", mistakes="wypychanie",
        easier="maszyna", harder="obciazenie_pauza",
    ),
    LibraryRow(
        "EX-BARKI-003", "Wyciskanie na maszynie nad głowę",
        "Machine Shoulder Press",
        "Barki",
        primary=("mięsień naramienny",),
        secondary=("triceps",),
        equipment=("maszyna",),
        level="początkujący", kind="wielostawowe",
        pattern="wypychanie pionowe",
        tags=("barki", "wypychanie pionowe", "wielostawowe"),
        benefit="barki", steps="wypychanie",
        breathing="napiecie", mistakes="wypychanie",
        easier="maszyna", harder="obciazenie_pauza",
    ),
    LibraryRow(
        "EX-BARKI-004", "Wyciskanie jednorącz półsztangi",
        "Landmine Press",
        "Barki",
        primary=("przednia część mięśnia naramiennego",),
        secondary=("górna klatka", "triceps", "zębaty przedni"),
        equipment=("półsztanga/landmine",),
        level="początkujący/średniozaawansowany", kind="wielostawowe",
        pattern="wypychanie skośne",
        tags=("barki", "wypychanie skośne", "wielostawowe"),
        benefit="barki", steps="wypychanie",
        breathing="napiecie", mistakes="wypychanie",
        easier="maszyna", harder="obciazenie_pauza",
    ),
    LibraryRow(
        "EX-BARKI-005", "Unoszenie hantli bokiem",
        "Dumbbell Lateral Raise",
        "Barki",
        primary=("boczna część mięśnia naramiennego",),
        secondary=("górny mięsień czworoboczny",),
        equipment=("hantle",),
        level="początkujący", kind="izolowane",
        pattern="odwodzenie ramienia",
        tags=("barki", "odwodzenie ramienia", "izolowane"),
        benefit="barki", steps="staw_ramienny",
        breathing="plynnie", mistakes="ogolne",
        easier="ogolna", harder="ogolna",
    ),
    LibraryRow(
        "EX-BARKI-006", "Unoszenie ramienia bokiem na wyciągu",
        "Cable Lateral Raise",
        "Barki",
        primary=("boczna część mięśnia naramiennego",),
        secondary=("mięsień czworoboczny",),
        equipment=("wyciąg dolny",),
        level="początkujący", kind="izolowane",
        pattern="odwodzenie ramienia",
        tags=("barki", "odwodzenie ramienia", "izolowane"),
        benefit="barki", steps="staw_ramienny",
        breathing="plynnie", mistakes="ogolne",
        easier="ogolna", harder="ogolna",
    ),
    LibraryRow(
        "EX-BARKI-007", "Unoszenie bokiem na maszynie",
        "Machine Lateral Raise",
        "Barki",
        primary=("boczna część mięśnia naramiennego",),
        secondary=("mięsień czworoboczny",),
        equipment=("maszyna",),
        level="początkujący", kind="izolowane",
        pattern="odwodzenie ramienia",
        tags=("barki", "odwodzenie ramienia", "izolowane"),
        benefit="barki", steps="staw_ramienny",
        breathing="plynnie", mistakes="ogolne",
        easier="ogolna", harder="ogolna",
    ),
    LibraryRow(
        "EX-BARKI-008", "Unoszenie hantli przodem",
        "Dumbbell Front Raise",
        "Barki",
        primary=("przednia część mięśnia naramiennego",),
        secondary=("górna część klatki",),
        equipment=("hantle",),
        level="początkujący", kind="izolowane",
        pattern="zgięcie ramienia",
        tags=("barki", "zgięcie ramienia", "izolowane"),
        benefit="barki", steps="staw_ramienny",
        breathing="plynnie", mistakes="ogolne",
        easier="ogolna", harder="ogolna",
    ),
    LibraryRow(
        "EX-BARKI-009", "Odwrotne rozpiętki z linkami",
        "Cable Rear Delt Fly",
        "Barki",
        primary=("tylna część mięśnia naramiennego",),
        secondary=("równoległoboczne", "mięsień czworoboczny"),
        equipment=("brama/wyciąg",),
        level="początkujący", kind="izolowane",
        pattern="odwodzenie poziome ramienia",
        tags=("barki", "odwodzenie poziome ramienia", "izolowane"),
        benefit="barki", steps="staw_ramienny",
        breathing="plynnie", mistakes="ogolne",
        easier="ogolna", harder="ogolna",
    ),
    LibraryRow(
        "EX-BARKI-010", "Wiosłowanie na tylny akton barków",
        "Rear Delt Row",
        "Barki",
        primary=("tylna część mięśnia naramiennego",),
        secondary=("górne plecy", "biceps"),
        equipment=("wyciąg/hantle",),
        level="średniozaawansowany", kind="wielostawowe",
        pattern="przyciąganie poziome",
        tags=("barki", "przyciąganie poziome", "wielostawowe"),
        benefit="barki", steps="przyciaganie_poziome",
        breathing="napiecie", mistakes="przyciaganie",
        easier="maszyna_wyciag", harder="obciazenie_pauza",
    ),
    # --- Biceps ---
    LibraryRow(
        "EX-BICEPS-001", "Uginanie ramion ze sztangą prostą",
        "Barbell Curl",
        "Biceps",
        primary=("mięsień dwugłowy ramienia",),
        secondary=("mięsień ramienny", "ramienno-promieniowy"),
        equipment=("sztanga",),
        level="początkujący", kind="izolowane",
        pattern="zgięcie łokcia",
        tags=("biceps", "zgięcie łokcia", "izolowane"),
        benefit="biceps", steps="zgiecie_lokcia",
        breathing="plynnie", mistakes="ogolne",
        easier="ogolna", harder="ogolna",
    ),
    LibraryRow(
        "EX-BICEPS-002", "Uginanie ramion ze sztangą łamaną",
        "EZ-Bar Curl",
        "Biceps",
        primary=("mięsień dwugłowy ramienia",),
        secondary=("mięsień ramienny", "przedramiona"),
        equipment=("sztanga EZ",),
        level="początkujący", kind="izolowane",
        pattern="zgięcie łokcia",
        tags=("biceps", "zgięcie łokcia", "izolowane"),
        benefit="biceps", steps="zgiecie_lokcia",
        breathing="plynnie", mistakes="ogolne",
        easier="ogolna", harder="ogolna",
    ),
    LibraryRow(
        "EX-BICEPS-003", "Uginanie hantli na ławce skośnej",
        "Incline Dumbbell Curl",
        "Biceps",
        primary=("mięsień dwugłowy ramienia",),
        secondary=("mięsień ramienny",),
        equipment=("hantle", "ławka regulowana"),
        level="początkujący/średniozaawansowany", kind="izolowane",
        pattern="zgięcie łokcia",
        tags=("biceps", "zgięcie łokcia", "izolowane"),
        benefit="biceps", steps="zgiecie_lokcia",
        breathing="plynnie", mistakes="ogolne",
        easier="ogolna", harder="ogolna",
    ),
    LibraryRow(
        "EX-BICEPS-004", "Uginanie ramion na modlitewniku",
        "Preacher Curl",
        "Biceps",
        primary=("mięsień dwugłowy ramienia",),
        secondary=("mięsień ramienny",),
        equipment=("modlitewnik", "sztanga EZ/hantle"),
        level="początkujący", kind="izolowane",
        pattern="zgięcie łokcia",
        tags=("biceps", "zgięcie łokcia", "izolowane"),
        benefit="biceps", steps="zgiecie_lokcia",
        breathing="plynnie", mistakes="ogolne",
        easier="ogolna", harder="ogolna",
    ),
    LibraryRow(
        "EX-BICEPS-005", "Uginanie ramion na wyciągu dolnym",
        "Cable Curl",
        "Biceps",
        primary=("mięsień dwugłowy ramienia",),
        secondary=("mięsień ramienny",),
        equipment=("wyciąg dolny",),
        level="początkujący", kind="izolowane",
        pattern="zgięcie łokcia",
        tags=("biceps", "zgięcie łokcia", "izolowane"),
        benefit="biceps", steps="zgiecie_lokcia",
        breathing="plynnie", mistakes="ogolne",
        easier="ogolna", harder="ogolna",
    ),
    LibraryRow(
        "EX-BICEPS-006", "Uginanie ramienia na wyciągu z ręką za tułowiem",
        "Bayesian Cable Curl",
        "Biceps",
        primary=("mięsień dwugłowy ramienia",),
        secondary=("mięsień ramienny",),
        equipment=("wyciąg dolny",),
        level="średniozaawansowany", kind="izolowane",
        pattern="zgięcie łokcia",
        tags=("biceps", "zgięcie łokcia", "izolowane"),
        benefit="biceps", steps="zgiecie_lokcia",
        breathing="plynnie", mistakes="ogolne",
        easier="ogolna", harder="ogolna",
    ),
    LibraryRow(
        "EX-BICEPS-007", "Uginanie młotkowe hantli",
        "Hammer Curl",
        "Biceps",
        primary=("mięsień ramienny", "ramienno-promieniowy"),
        secondary=("biceps",),
        equipment=("hantle",),
        level="początkujący", kind="izolowane",
        pattern="zgięcie łokcia",
        tags=("biceps", "zgięcie łokcia", "izolowane"),
        benefit="biceps", steps="zgiecie_lokcia",
        breathing="plynnie", mistakes="ogolne",
        easier="ogolna", harder="ogolna",
    ),
    LibraryRow(
        "EX-BICEPS-008", "Uginanie młotkowe w poprzek tułowia",
        "Cross-Body Hammer Curl",
        "Biceps",
        primary=("mięsień ramienno-promieniowy", "ramienny"),
        secondary=("biceps",),
        equipment=("hantle",),
        level="początkujący", kind="izolowane",
        pattern="zgięcie łokcia",
        tags=("biceps", "zgięcie łokcia", "izolowane"),
        benefit="biceps", steps="zgiecie_lokcia",
        breathing="plynnie", mistakes="ogolne",
        easier="ogolna", harder="ogolna",
    ),
    LibraryRow(
        "EX-BICEPS-009", "Uginanie koncentryczne w podporze o udo",
        "Concentration Curl",
        "Biceps",
        primary=("mięsień dwugłowy ramienia",),
        secondary=("mięsień ramienny",),
        equipment=("hantel",),
        level="początkujący", kind="izolowane",
        pattern="zgięcie łokcia",
        tags=("biceps", "zgięcie łokcia", "izolowane"),
        benefit="biceps", steps="zgiecie_lokcia",
        breathing="plynnie", mistakes="ogolne",
        easier="ogolna", harder="ogolna",
    ),
    LibraryRow(
        "EX-BICEPS-010", "Uginanie ramion leżąc przodem na ławce skośnej",
        "Spider Curl",
        "Biceps",
        primary=("mięsień dwugłowy ramienia",),
        secondary=("mięsień ramienny",),
        equipment=("hantle/sztanga EZ", "ławka"),
        level="średniozaawansowany", kind="izolowane",
        pattern="zgięcie łokcia",
        tags=("biceps", "zgięcie łokcia", "izolowane"),
        benefit="biceps", steps="zgiecie_lokcia",
        breathing="plynnie", mistakes="ogolne",
        easier="ogolna", harder="ogolna",
    ),
    # --- Triceps ---
    LibraryRow(
        "EX-TRICEPS-001", "Prostowanie ramion na wyciągu z liną",
        "Rope Triceps Pushdown",
        "Triceps",
        primary=("mięsień trójgłowy ramienia",),
        secondary=(),
        equipment=("wyciąg górny", "lina"),
        level="początkujący", kind="izolowane",
        pattern="wyprost łokcia",
        tags=("triceps", "wyprost łokcia", "izolowane"),
        benefit="triceps", steps="wyprost_lokcia",
        breathing="plynnie", mistakes="ogolne",
        easier="ogolna", harder="ogolna",
    ),
    LibraryRow(
        "EX-TRICEPS-002", "Prostowanie ramion na wyciągu z drążkiem",
        "Bar Triceps Pushdown",
        "Triceps",
        primary=("mięsień trójgłowy ramienia",),
        secondary=(),
        equipment=("wyciąg górny", "drążek"),
        level="początkujący", kind="izolowane",
        pattern="wyprost łokcia",
        tags=("triceps", "wyprost łokcia", "izolowane"),
        benefit="triceps", steps="wyprost_lokcia",
        breathing="plynnie", mistakes="ogolne",
        easier="ogolna", harder="ogolna",
    ),
    LibraryRow(
        "EX-TRICEPS-003", "Prostowanie ramion nad głową z liną",
        "Overhead Rope Triceps Extension",
        "Triceps",
        primary=("mięsień trójgłowy ramienia — szczególnie głowa długa",),
        secondary=(),
        equipment=("wyciąg", "lina"),
        level="początkujący/średniozaawansowany", kind="izolowane",
        pattern="wyprost łokcia",
        tags=("triceps", "wyprost łokcia", "izolowane"),
        benefit="triceps", steps="wyprost_lokcia",
        breathing="plynnie", mistakes="ogolne",
        easier="ogolna", harder="ogolna",
    ),
    LibraryRow(
        "EX-TRICEPS-004", "Wyciskanie francuskie sztangą łamaną leżąc",
        "EZ-Bar Lying Triceps Extension",
        "Triceps",
        primary=("mięsień trójgłowy ramienia",),
        secondary=(),
        equipment=("sztanga EZ", "ławka"),
        level="średniozaawansowany", kind="izolowane",
        pattern="wyprost łokcia",
        tags=("triceps", "wyprost łokcia", "izolowane"),
        benefit="triceps", steps="wyprost_lokcia",
        breathing="plynnie", mistakes="ogolne",
        easier="ogolna", harder="ogolna",
    ),
    LibraryRow(
        "EX-TRICEPS-005", "Prostowanie hantla jednorącz zza głowy",
        "Single-Arm Overhead Dumbbell Extension",
        "Triceps",
        primary=("mięsień trójgłowy ramienia — głowa długa",),
        secondary=(),
        equipment=("hantel",),
        level="początkujący", kind="izolowane",
        pattern="wyprost łokcia",
        tags=("triceps", "wyprost łokcia", "izolowane"),
        benefit="triceps", steps="wyprost_lokcia",
        breathing="plynnie", mistakes="ogolne",
        easier="ogolna", harder="ogolna",
    ),
    LibraryRow(
        "EX-TRICEPS-006", "Wyciskanie sztangi wąskim chwytem",
        "Close-Grip Bench Press",
        "Triceps",
        primary=("mięsień trójgłowy ramienia",),
        secondary=("klatka piersiowa", "przedni bark"),
        equipment=("sztanga", "ławka", "stojaki"),
        level="średniozaawansowany", kind="wielostawowe",
        pattern="wypychanie poziome",
        tags=("triceps", "wypychanie poziome", "wielostawowe"),
        benefit="triceps", steps="wypychanie",
        breathing="napiecie", mistakes="wypychanie",
        easier="maszyna", harder="obciazenie_pauza",
    ),
    LibraryRow(
        "EX-TRICEPS-007", "Pompki na poręczach z naciskiem na triceps",
        "Triceps Dip",
        "Triceps",
        primary=("mięsień trójgłowy ramienia",),
        secondary=("klatka", "przedni bark"),
        equipment=("poręcze",),
        level="średniozaawansowany", kind="wielostawowe",
        pattern="wypychanie pionowe",
        tags=("triceps", "wypychanie pionowe", "wielostawowe"),
        benefit="triceps", steps="wypychanie",
        breathing="napiecie", mistakes="wypychanie",
        easier="pompki", harder="zakres",
    ),
    LibraryRow(
        "EX-TRICEPS-008", "Prostowanie ramienia na wyciągu jednorącz",
        "Single-Arm Cable Pushdown",
        "Triceps",
        primary=("mięsień trójgłowy ramienia",),
        secondary=(),
        equipment=("wyciąg",),
        level="początkujący", kind="izolowane",
        pattern="wyprost łokcia",
        tags=("triceps", "wyprost łokcia", "izolowane"),
        benefit="triceps", steps="wyprost_lokcia",
        breathing="plynnie", mistakes="ogolne",
        easier="ogolna", harder="ogolna",
    ),
    LibraryRow(
        "EX-TRICEPS-009", "Prostowanie ramion na maszynie",
        "Machine Triceps Extension",
        "Triceps",
        primary=("mięsień trójgłowy ramienia",),
        secondary=(),
        equipment=("maszyna",),
        level="początkujący", kind="izolowane",
        pattern="wyprost łokcia",
        tags=("triceps", "wyprost łokcia", "izolowane"),
        benefit="triceps", steps="wyprost_lokcia",
        breathing="plynnie", mistakes="ogolne",
        easier="ogolna", harder="ogolna",
    ),
    LibraryRow(
        "EX-TRICEPS-010", "Pompki w podporze tyłem na ławce",
        "Bench Dip",
        "Triceps",
        primary=("mięsień trójgłowy ramienia",),
        secondary=("przedni bark", "klatka"),
        equipment=("ławka", "masa własnego ciała"),
        level="początkujący/średniozaawansowany", kind="wielostawowe",
        pattern="wyprost łokcia/wypychanie",
        tags=("triceps", "wyprost łokcia/wypychanie", "wielostawowe"),
        benefit="triceps", steps="wypychanie",
        breathing="napiecie", mistakes="wypychanie",
        easier="pompki", harder="zakres",
    ),
    # --- Mięśnie czworogłowe uda ---
    LibraryRow(
        "EX-QUAD-001", "Przysiad ze sztangą na plecach",
        "Barbell Back Squat",
        "Mięśnie czworogłowe uda",
        primary=("mięsień czworogłowy uda",),
        secondary=("pośladkowy wielki", "przywodziciele", "core"),
        equipment=("sztanga", "stojaki"),
        level="średniozaawansowany", kind="wielostawowe",
        pattern="przysiad",
        tags=("mięśnie czworogłowe uda", "przysiad", "wielostawowe"),
        benefit="czworoglowy", steps="przysiad",
        breathing="napiecie", mistakes="nogi",
        easier="przysiad", harder="obciazenie_pauza",
    ),
    LibraryRow(
        "EX-QUAD-002", "Przysiad ze sztangą z przodu",
        "Front Squat",
        "Mięśnie czworogłowe uda",
        primary=("mięsień czworogłowy uda",),
        secondary=("pośladki", "górne plecy", "core"),
        equipment=("sztanga", "stojaki"),
        level="średniozaawansowany", kind="wielostawowe",
        pattern="przysiad",
        tags=("mięśnie czworogłowe uda", "przysiad", "wielostawowe"),
        benefit="czworoglowy", steps="przysiad",
        breathing="napiecie", mistakes="nogi",
        easier="przysiad", harder="obciazenie_pauza",
    ),
    LibraryRow(
        "EX-QUAD-003", "Przysiad na maszynie Hack",
        "Hack Squat",
        "Mięśnie czworogłowe uda",
        primary=("mięsień czworogłowy uda",),
        secondary=("pośladki", "przywodziciele"),
        equipment=("maszyna Hack",),
        level="początkujący/średniozaawansowany", kind="wielostawowe",
        pattern="przysiad",
        tags=("mięśnie czworogłowe uda", "przysiad", "wielostawowe"),
        benefit="czworoglowy", steps="przysiad",
        breathing="napiecie", mistakes="nogi",
        easier="przysiad", harder="obciazenie_pauza",
    ),
    LibraryRow(
        "EX-QUAD-004", "Wypychanie nóg na suwnicy",
        "Leg Press",
        "Mięśnie czworogłowe uda",
        primary=("mięsień czworogłowy uda",),
        secondary=("pośladki", "przywodziciele"),
        equipment=("suwnica",),
        level="początkujący", kind="wielostawowe",
        pattern="przysiad/wypychanie nóg",
        tags=("mięśnie czworogłowe uda", "przysiad/wypychanie nóg", "wielostawowe"),
        benefit="czworoglowy", steps="przysiad",
        breathing="napiecie", mistakes="nogi",
        easier="przysiad", harder="obciazenie_pauza",
    ),
    LibraryRow(
        "EX-QUAD-005", "Prostowanie nóg na maszynie",
        "Leg Extension",
        "Mięśnie czworogłowe uda",
        primary=("mięsień czworogłowy uda",),
        secondary=(),
        equipment=("maszyna",),
        level="początkujący", kind="izolowane",
        pattern="wyprost kolana",
        tags=("mięśnie czworogłowe uda", "wyprost kolana", "izolowane"),
        benefit="czworoglowy", steps="wyprost_kolana",
        breathing="plynnie", mistakes="ogolne",
        easier="ogolna", harder="ogolna",
    ),
    LibraryRow(
        "EX-QUAD-006", "Przysiad bułgarski z naciskiem na przód uda",
        "Quad-Biased Bulgarian Split Squat",
        "Mięśnie czworogłowe uda",
        primary=("mięsień czworogłowy uda",),
        secondary=("pośladki", "przywodziciele"),
        equipment=("hantle", "ławka"),
        level="średniozaawansowany", kind="wielostawowe",
        pattern="wykrok/przysiad jednonóż",
        tags=("mięśnie czworogłowe uda", "wykrok/przysiad jednonóż", "wielostawowe"),
        benefit="czworoglowy", steps="przysiad",
        breathing="napiecie", mistakes="nogi",
        easier="przysiad", harder="obciazenie_pauza",
    ),
    LibraryRow(
        "EX-QUAD-007", "Przysiad z hantlem i uniesionymi piętami",
        "Heel-Elevated Goblet Squat",
        "Mięśnie czworogłowe uda",
        primary=("mięsień czworogłowy uda",),
        secondary=("pośladki", "core"),
        equipment=("hantel/kettlebell", "podkładka pod pięty"),
        level="początkujący", kind="wielostawowe",
        pattern="przysiad",
        tags=("mięśnie czworogłowe uda", "przysiad", "wielostawowe"),
        benefit="czworoglowy", steps="przysiad",
        breathing="napiecie", mistakes="nogi",
        easier="przysiad", harder="obciazenie_pauza",
    ),
    LibraryRow(
        "EX-QUAD-008", "Wejście na podwyższenie",
        "Step-Up",
        "Mięśnie czworogłowe uda",
        primary=("mięsień czworogłowy uda",),
        secondary=("pośladki", "tylna część uda"),
        equipment=("podest", "hantle opcjonalnie"),
        level="początkujący/średniozaawansowany", kind="wielostawowe",
        pattern="wejście/praca jednonóż",
        tags=("mięśnie czworogłowe uda", "wejście/praca jednonóż", "wielostawowe"),
        benefit="czworoglowy", steps="jednonoz",
        breathing="napiecie", mistakes="nogi",
        easier="ogolna", harder="ogolna",
    ),
    LibraryRow(
        "EX-QUAD-009", "Wykroki chodzone",
        "Walking Lunge",
        "Mięśnie czworogłowe uda",
        primary=("mięsień czworogłowy uda",),
        secondary=("pośladki", "przywodziciele", "core"),
        equipment=("hantle/sztanga opcjonalnie",),
        level="średniozaawansowany", kind="wielostawowe",
        pattern="wykrok",
        tags=("mięśnie czworogłowe uda", "wykrok", "wielostawowe"),
        benefit="czworoglowy", steps="jednonoz",
        breathing="napiecie", mistakes="nogi",
        easier="ogolna", harder="ogolna",
    ),
    LibraryRow(
        "EX-QUAD-010", "Przysiad na maszynie Smitha z uniesionymi piętami",
        "Smith Machine Heel-Elevated Squat",
        "Mięśnie czworogłowe uda",
        primary=("mięsień czworogłowy uda",),
        secondary=("pośladki",),
        equipment=("maszyna Smitha", "podkładka"),
        level="początkujący/średniozaawansowany", kind="wielostawowe",
        pattern="przysiad",
        tags=("mięśnie czworogłowe uda", "przysiad", "wielostawowe"),
        benefit="czworoglowy", steps="przysiad",
        breathing="napiecie", mistakes="nogi",
        easier="przysiad", harder="obciazenie_pauza",
    ),
    # --- Tylna część uda ---
    LibraryRow(
        "EX-HAM-001", "Martwy ciąg rumuński ze sztangą",
        "Barbell Romanian Deadlift",
        "Tylna część uda",
        primary=("mięśnie kulszowo-goleniowe",),
        secondary=("pośladkowy wielki", "prostowniki grzbietu"),
        equipment=("sztanga",),
        level="średniozaawansowany", kind="wielostawowe",
        pattern="zawias biodrowy",
        tags=("tylna część uda", "zawias biodrowy", "wielostawowe"),
        benefit="kulszowo_goleniowe", steps="zawias",
        breathing="napiecie", mistakes="zawias",
        easier="zawias", harder="obciazenie_pauza",
    ),
    LibraryRow(
        "EX-HAM-002", "Martwy ciąg rumuński z hantlami",
        "Dumbbell Romanian Deadlift",
        "Tylna część uda",
        primary=("mięśnie kulszowo-goleniowe",),
        secondary=("pośladki", "prostowniki grzbietu"),
        equipment=("hantle",),
        level="początkujący/średniozaawansowany", kind="wielostawowe",
        pattern="zawias biodrowy",
        tags=("tylna część uda", "zawias biodrowy", "wielostawowe"),
        benefit="kulszowo_goleniowe", steps="zawias",
        breathing="napiecie", mistakes="zawias",
        easier="zawias", harder="obciazenie_pauza",
    ),
    LibraryRow(
        "EX-HAM-003", "Uginanie nóg siedząc na maszynie",
        "Seated Leg Curl",
        "Tylna część uda",
        primary=("mięśnie kulszowo-goleniowe",),
        secondary=("mięsień brzuchaty łydki",),
        equipment=("maszyna",),
        level="początkujący", kind="izolowane",
        pattern="zgięcie kolana",
        tags=("tylna część uda", "zgięcie kolana", "izolowane"),
        benefit="kulszowo_goleniowe", steps="zgiecie_kolana",
        breathing="plynnie", mistakes="ogolne",
        easier="ogolna", harder="ogolna",
    ),
    LibraryRow(
        "EX-HAM-004", "Uginanie nóg leżąc na maszynie",
        "Lying Leg Curl",
        "Tylna część uda",
        primary=("mięśnie kulszowo-goleniowe",),
        secondary=("mięsień brzuchaty łydki",),
        equipment=("maszyna",),
        level="początkujący", kind="izolowane",
        pattern="zgięcie kolana",
        tags=("tylna część uda", "zgięcie kolana", "izolowane"),
        benefit="kulszowo_goleniowe", steps="zgiecie_kolana",
        breathing="plynnie", mistakes="ogolne",
        easier="ogolna", harder="ogolna",
    ),
    LibraryRow(
        "EX-HAM-005", "Uginanie nogi stojąc na maszynie",
        "Standing Single-Leg Curl",
        "Tylna część uda",
        primary=("mięśnie kulszowo-goleniowe",),
        secondary=("mięsień brzuchaty łydki",),
        equipment=("maszyna",),
        level="początkujący", kind="izolowane",
        pattern="zgięcie kolana",
        tags=("tylna część uda", "zgięcie kolana", "izolowane"),
        benefit="kulszowo_goleniowe", steps="zgiecie_kolana",
        breathing="plynnie", mistakes="ogolne",
        easier="ogolna", harder="ogolna",
    ),
    LibraryRow(
        "EX-HAM-006", "Nordyckie uginanie nóg",
        "Nordic Hamstring Curl",
        "Tylna część uda",
        primary=("mięśnie kulszowo-goleniowe",),
        secondary=("pośladki", "mięśnie łydki"),
        equipment=("stanowisko/partner", "masa własnego ciała"),
        level="zaawansowany", kind="wielostawowe",
        pattern="zgięcie kolana — ekscentryczne",
        tags=("tylna część uda", "zgięcie kolana — ekscentryczne", "wielostawowe"),
        benefit="kulszowo_goleniowe", steps="zgiecie_kolana",
        breathing="plynnie", mistakes="ogolne",
        easier="ogolna", harder="ogolna",
    ),
    LibraryRow(
        "EX-HAM-007", "Skłon dzień dobry ze sztangą",
        "Barbell Good Morning",
        "Tylna część uda",
        primary=("mięśnie kulszowo-goleniowe",),
        secondary=("pośladki", "prostowniki grzbietu"),
        equipment=("sztanga", "stojaki"),
        level="średniozaawansowany/zaawansowany", kind="wielostawowe",
        pattern="zawias biodrowy",
        tags=("tylna część uda", "zawias biodrowy", "wielostawowe"),
        benefit="kulszowo_goleniowe", steps="zawias",
        breathing="napiecie", mistakes="zawias",
        easier="zawias", harder="obciazenie_pauza",
    ),
    LibraryRow(
        "EX-HAM-008", "Martwy ciąg rumuński jednonóż",
        "Single-Leg Romanian Deadlift",
        "Tylna część uda",
        primary=("mięśnie kulszowo-goleniowe",),
        secondary=("pośladki", "mięśnie stabilizujące biodro", "core"),
        equipment=("hantel/kettlebell",),
        level="średniozaawansowany", kind="wielostawowe",
        pattern="zawias biodrowy jednonóż",
        tags=("tylna część uda", "zawias biodrowy jednonóż", "wielostawowe"),
        benefit="kulszowo_goleniowe", steps="zawias",
        breathing="napiecie", mistakes="zawias",
        easier="zawias", harder="obciazenie_pauza",
    ),
    LibraryRow(
        "EX-HAM-009", "Uginanie nóg na piłce gimnastycznej",
        "Swiss-Ball Leg Curl",
        "Tylna część uda",
        primary=("mięśnie kulszowo-goleniowe",),
        secondary=("pośladki", "core"),
        equipment=("piłka gimnastyczna",),
        level="średniozaawansowany", kind="wielostawowe",
        pattern="zgięcie kolana/wyprost biodra",
        tags=("tylna część uda", "zgięcie kolana/wyprost biodra", "wielostawowe"),
        benefit="kulszowo_goleniowe", steps="zgiecie_kolana",
        breathing="plynnie", mistakes="ogolne",
        easier="ogolna", harder="ogolna",
    ),
    LibraryRow(
        "EX-HAM-010", "Uginanie nóg ze ślizgaczami",
        "Slider Leg Curl",
        "Tylna część uda",
        primary=("mięśnie kulszowo-goleniowe",),
        secondary=("pośladki", "core"),
        equipment=("ślizgacze/ręczniki",),
        level="średniozaawansowany", kind="wielostawowe",
        pattern="zgięcie kolana/wyprost biodra",
        tags=("tylna część uda", "zgięcie kolana/wyprost biodra", "wielostawowe"),
        benefit="kulszowo_goleniowe", steps="zgiecie_kolana",
        breathing="plynnie", mistakes="ogolne",
        easier="ogolna", harder="ogolna",
    ),
    # --- Pośladki ---
    LibraryRow(
        "EX-POSL-001", "Unoszenie bioder ze sztangą",
        "Barbell Hip Thrust",
        "Pośladki",
        primary=("mięsień pośladkowy wielki",),
        secondary=("tylna część uda", "przywodziciele"),
        equipment=("sztanga", "ławka"),
        level="początkujący/średniozaawansowany", kind="wielostawowe",
        pattern="wyprost biodra",
        tags=("pośladki", "wyprost biodra", "wielostawowe"),
        benefit="posladki", steps="wyprost_biodra",
        breathing="plynnie", mistakes="ogolne",
        easier="ogolna", harder="ogolna",
    ),
    LibraryRow(
        "EX-POSL-002", "Most biodrowy",
        "Glute Bridge",
        "Pośladki",
        primary=("mięsień pośladkowy wielki",),
        secondary=("tylna część uda", "core"),
        equipment=("masa własnego ciała/obciążenie",),
        level="początkujący", kind="wielostawowe",
        pattern="wyprost biodra",
        tags=("pośladki", "wyprost biodra", "wielostawowe"),
        benefit="posladki", steps="wyprost_biodra",
        breathing="plynnie", mistakes="ogolne",
        easier="ogolna", harder="ogolna",
    ),
    LibraryRow(
        "EX-POSL-003", "Przysiad bułgarski z naciskiem na pośladki",
        "Glute-Biased Bulgarian Split Squat",
        "Pośladki",
        primary=("mięsień pośladkowy wielki",),
        secondary=("czworogłowy uda", "przywodziciele"),
        equipment=("hantle", "ławka"),
        level="średniozaawansowany", kind="wielostawowe",
        pattern="wykrok/praca jednonóż",
        tags=("pośladki", "wykrok/praca jednonóż", "wielostawowe"),
        benefit="posladki", steps="jednonoz",
        breathing="napiecie", mistakes="nogi",
        easier="ogolna", harder="ogolna",
    ),
    LibraryRow(
        "EX-POSL-004", "Wykrok w tył",
        "Reverse Lunge",
        "Pośladki",
        primary=("mięsień pośladkowy wielki",),
        secondary=("czworogłowy uda", "przywodziciele"),
        equipment=("hantle opcjonalnie",),
        level="początkujący/średniozaawansowany", kind="wielostawowe",
        pattern="wykrok",
        tags=("pośladki", "wykrok", "wielostawowe"),
        benefit="posladki", steps="jednonoz",
        breathing="napiecie", mistakes="nogi",
        easier="ogolna", harder="ogolna",
    ),
    LibraryRow(
        "EX-POSL-005", "Prostowanie nogi w tył na wyciągu",
        "Cable Glute Kickback",
        "Pośladki",
        primary=("mięsień pośladkowy wielki",),
        secondary=("tylna część uda",),
        equipment=("wyciąg dolny", "opaska na kostkę"),
        level="początkujący", kind="izolowane",
        pattern="wyprost biodra",
        tags=("pośladki", "wyprost biodra", "izolowane"),
        benefit="posladki", steps="wyprost_biodra",
        breathing="plynnie", mistakes="ogolne",
        easier="ogolna", harder="ogolna",
    ),
    LibraryRow(
        "EX-POSL-006", "Wyprost tułowia na ławce 45° z naciskiem na pośladki",
        "Glute-Biased 45° Back Extension",
        "Pośladki",
        primary=("mięsień pośladkowy wielki",),
        secondary=("tylna część uda", "prostowniki grzbietu"),
        equipment=("ławka rzymska 45°",),
        level="średniozaawansowany", kind="wielostawowe",
        pattern="wyprost biodra",
        tags=("pośladki", "wyprost biodra", "wielostawowe"),
        benefit="posladki", steps="wyprost_biodra",
        breathing="plynnie", mistakes="ogolne",
        easier="ogolna", harder="ogolna",
    ),
    LibraryRow(
        "EX-POSL-007", "Wysokie wejście na podwyższenie",
        "High Step-Up",
        "Pośladki",
        primary=("mięsień pośladkowy wielki",),
        secondary=("czworogłowy uda", "tylna część uda"),
        equipment=("wysoki podest", "hantle opcjonalnie"),
        level="średniozaawansowany", kind="wielostawowe",
        pattern="wejście/praca jednonóż",
        tags=("pośladki", "wejście/praca jednonóż", "wielostawowe"),
        benefit="posladki", steps="jednonoz",
        breathing="napiecie", mistakes="nogi",
        easier="ogolna", harder="ogolna",
    ),
    LibraryRow(
        "EX-POSL-008", "Przysiad sumo z hantlem",
        "Dumbbell Sumo Squat",
        "Pośladki",
        primary=("pośladki", "przywodziciele"),
        secondary=("czworogłowy uda",),
        equipment=("hantel/kettlebell",),
        level="początkujący", kind="wielostawowe",
        pattern="przysiad",
        tags=("pośladki", "przysiad", "wielostawowe"),
        benefit="posladki", steps="przysiad",
        breathing="napiecie", mistakes="nogi",
        easier="przysiad", harder="obciazenie_pauza",
    ),
    LibraryRow(
        "EX-POSL-009", "Odwodzenie nóg na maszynie",
        "Hip Abduction Machine",
        "Pośladki",
        primary=("mięsień pośladkowy średni i mały",),
        secondary=("górne włókna pośladkowego wielkiego",),
        equipment=("maszyna",),
        level="początkujący", kind="izolowane",
        pattern="odwodzenie biodra",
        tags=("pośladki", "odwodzenie biodra", "izolowane"),
        benefit="posladki", steps="staw_ramienny",
        breathing="plynnie", mistakes="ogolne",
        easier="ogolna", harder="ogolna",
    ),
    LibraryRow(
        "EX-POSL-010", "Odwodzenie nogi na wyciągu",
        "Cable Hip Abduction",
        "Pośladki",
        primary=("mięsień pośladkowy średni i mały",),
        secondary=("mięśnie stabilizujące biodro",),
        equipment=("wyciąg dolny", "opaska"),
        level="początkujący", kind="izolowane",
        pattern="odwodzenie biodra",
        tags=("pośladki", "odwodzenie biodra", "izolowane"),
        benefit="posladki", steps="staw_ramienny",
        breathing="plynnie", mistakes="ogolne",
        easier="ogolna", harder="ogolna",
    ),
    # --- Łydki i podudzie ---
    LibraryRow(
        "EX-LYDKA-001", "Wspięcia na palce stojąc na maszynie",
        "Standing Calf Raise",
        "Łydki i podudzie",
        primary=("mięsień brzuchaty łydki",),
        secondary=("mięsień płaszczkowaty",),
        equipment=("maszyna",),
        level="początkujący", kind="izolowane",
        pattern="zgięcie podeszwowe stopy",
        tags=("łydki i podudzie", "zgięcie podeszwowe stopy", "izolowane"),
        benefit="podudzie", steps="wspiecie",
        breathing="plynnie", mistakes="ogolne",
        easier="ogolna", harder="ogolna",
    ),
    LibraryRow(
        "EX-LYDKA-002", "Wspięcia na palce siedząc",
        "Seated Calf Raise",
        "Łydki i podudzie",
        primary=("mięsień płaszczkowaty",),
        secondary=("mięsień brzuchaty łydki",),
        equipment=("maszyna",),
        level="początkujący", kind="izolowane",
        pattern="zgięcie podeszwowe stopy",
        tags=("łydki i podudzie", "zgięcie podeszwowe stopy", "izolowane"),
        benefit="podudzie", steps="wspiecie",
        breathing="plynnie", mistakes="ogolne",
        easier="ogolna", harder="ogolna",
    ),
    LibraryRow(
        "EX-LYDKA-003", "Wspięcia na palce jednonóż",
        "Single-Leg Calf Raise",
        "Łydki i podudzie",
        primary=("mięśnie łydki",),
        secondary=("mięśnie stopy",),
        equipment=("podwyższenie", "obciążenie opcjonalnie"),
        level="początkujący/średniozaawansowany", kind="izolowane",
        pattern="zgięcie podeszwowe stopy",
        tags=("łydki i podudzie", "zgięcie podeszwowe stopy", "izolowane"),
        benefit="podudzie", steps="wspiecie",
        breathing="plynnie", mistakes="ogolne",
        easier="ogolna", harder="ogolna",
    ),
    LibraryRow(
        "EX-LYDKA-004", "Wspięcia na palce na suwnicy",
        "Leg Press Calf Raise",
        "Łydki i podudzie",
        primary=("mięsień brzuchaty łydki",),
        secondary=("płaszczkowaty",),
        equipment=("suwnica",),
        level="początkujący", kind="izolowane",
        pattern="zgięcie podeszwowe stopy",
        tags=("łydki i podudzie", "zgięcie podeszwowe stopy", "izolowane"),
        benefit="podudzie", steps="wspiecie",
        breathing="plynnie", mistakes="ogolne",
        easier="ogolna", harder="ogolna",
    ),
    LibraryRow(
        "EX-LYDKA-005", "Wspięcia na palce na maszynie Smitha",
        "Smith Machine Calf Raise",
        "Łydki i podudzie",
        primary=("mięsień brzuchaty łydki",),
        secondary=("płaszczkowaty",),
        equipment=("maszyna Smitha", "podwyższenie"),
        level="początkujący/średniozaawansowany", kind="izolowane",
        pattern="zgięcie podeszwowe stopy",
        tags=("łydki i podudzie", "zgięcie podeszwowe stopy", "izolowane"),
        benefit="podudzie", steps="wspiecie",
        breathing="plynnie", mistakes="ogolne",
        easier="ogolna", harder="ogolna",
    ),
    LibraryRow(
        "EX-LYDKA-006", "Wspięcia na palce z hantlami",
        "Dumbbell Calf Raise",
        "Łydki i podudzie",
        primary=("mięsień brzuchaty łydki",),
        secondary=("płaszczkowaty", "chwyt"),
        equipment=("hantle", "podwyższenie"),
        level="początkujący", kind="izolowane",
        pattern="zgięcie podeszwowe stopy",
        tags=("łydki i podudzie", "zgięcie podeszwowe stopy", "izolowane"),
        benefit="podudzie", steps="wspiecie",
        breathing="plynnie", mistakes="ogolne",
        easier="ogolna", harder="ogolna",
    ),
    LibraryRow(
        "EX-LYDKA-007", "Wspięcia siedząc jednonóż",
        "Single-Leg Seated Calf Raise",
        "Łydki i podudzie",
        primary=("mięsień płaszczkowaty",),
        secondary=("brzuchaty łydki",),
        equipment=("hantel", "ławka"),
        level="początkujący", kind="izolowane",
        pattern="zgięcie podeszwowe stopy",
        tags=("łydki i podudzie", "zgięcie podeszwowe stopy", "izolowane"),
        benefit="podudzie", steps="wspiecie",
        breathing="plynnie", mistakes="ogolne",
        easier="ogolna", harder="ogolna",
    ),
    LibraryRow(
        "EX-LYDKA-008", "Wspięcia na palce z pauzą w rozciągnięciu",
        "Paused Calf Raise",
        "Łydki i podudzie",
        primary=("mięśnie łydki",),
        secondary=("mięśnie stopy",),
        equipment=("maszyna/podwyższenie",),
        level="średniozaawansowany", kind="izolowane",
        pattern="zgięcie podeszwowe stopy",
        tags=("łydki i podudzie", "zgięcie podeszwowe stopy", "izolowane"),
        benefit="podudzie", steps="wspiecie",
        breathing="plynnie", mistakes="ogolne",
        easier="ogolna", harder="ogolna",
    ),
    LibraryRow(
        "EX-LYDKA-009", "Unoszenie palców stóp stojąc przy ścianie",
        "Tibialis Raise",
        "Łydki i podudzie",
        primary=("mięsień piszczelowy przedni",),
        secondary=("prostowniki palców",),
        equipment=("ściana/masa własnego ciała",),
        level="początkujący", kind="izolowane",
        pattern="zgięcie grzbietowe stopy",
        tags=("łydki i podudzie", "zgięcie grzbietowe stopy", "izolowane"),
        benefit="podudzie", steps="zgiecie_grzbietowe",
        breathing="plynnie", mistakes="ogolne",
        easier="ogolna", harder="ogolna",
    ),
    LibraryRow(
        "EX-LYDKA-010", "Unoszenie palców na maszynie lub z obciążeniem",
        "Weighted Tibialis Raise",
        "Łydki i podudzie",
        primary=("mięsień piszczelowy przedni",),
        secondary=("prostowniki palców",),
        equipment=("maszyna/obciążenie",),
        level="średniozaawansowany", kind="izolowane",
        pattern="zgięcie grzbietowe stopy",
        tags=("łydki i podudzie", "zgięcie grzbietowe stopy", "izolowane"),
        benefit="podudzie", steps="zgiecie_grzbietowe",
        breathing="plynnie", mistakes="ogolne",
        easier="ogolna", harder="ogolna",
    ),
    # --- Brzuch i mięśnie głębokie ---
    LibraryRow(
        "EX-CORE-001", "Spięcia brzucha na wyciągu",
        "Cable Crunch",
        "Brzuch i mięśnie głębokie",
        primary=("mięsień prosty brzucha",),
        secondary=("mięśnie skośne", "poprzeczny brzucha"),
        equipment=("wyciąg górny", "lina"),
        level="początkujący/średniozaawansowany", kind="izolowane",
        pattern="zgięcie tułowia",
        tags=("brzuch i mięśnie głębokie", "zgięcie tułowia", "izolowane"),
        benefit="tulow", steps="ogolny",
        breathing="plynnie", mistakes="ogolne",
        easier="ogolna", harder="ogolna",
    ),
    LibraryRow(
        "EX-CORE-002", "Wytaczanie kółka do brzucha",
        "Ab Wheel Rollout",
        "Brzuch i mięśnie głębokie",
        primary=("mięśnie brzucha i głębokie tułowia",),
        secondary=("najszerszy grzbietu", "zębaty przedni", "pośladki"),
        equipment=("kółko do brzucha",),
        level="średniozaawansowany", kind="wielostawowe",
        pattern="antywyprost",
        tags=("brzuch i mięśnie głębokie", "antywyprost", "wielostawowe"),
        benefit="tulow", steps="stabilizacja",
        breathing="plynnie", mistakes="ogolne",
        easier="dzwignia", harder="ogolna",
    ),
    LibraryRow(
        "EX-CORE-003", "Unoszenie kolan w zwisie",
        "Hanging Knee Raise",
        "Brzuch i mięśnie głębokie",
        primary=("mięsień prosty brzucha",),
        secondary=("zginacze biodra", "mięśnie skośne"),
        equipment=("drążek",),
        level="średniozaawansowany", kind="wielostawowe",
        pattern="zgięcie miednicy/tułowia",
        tags=("brzuch i mięśnie głębokie", "zgięcie miednicy/tułowia", "wielostawowe"),
        benefit="tulow", steps="ogolny",
        breathing="plynnie", mistakes="ogolne",
        easier="ogolna", harder="ogolna",
    ),
    LibraryRow(
        "EX-CORE-004", "Unoszenie prostych nóg w zwisie",
        "Hanging Leg Raise",
        "Brzuch i mięśnie głębokie",
        primary=("mięsień prosty brzucha",),
        secondary=("zginacze biodra", "mięśnie skośne"),
        equipment=("drążek",),
        level="zaawansowany", kind="wielostawowe",
        pattern="zgięcie miednicy/tułowia",
        tags=("brzuch i mięśnie głębokie", "zgięcie miednicy/tułowia", "wielostawowe"),
        benefit="tulow", steps="ogolny",
        breathing="plynnie", mistakes="ogolne",
        easier="ogolna", harder="ogolna",
    ),
    LibraryRow(
        "EX-CORE-005", "Odwrotne spięcia brzucha",
        "Reverse Crunch",
        "Brzuch i mięśnie głębokie",
        primary=("mięsień prosty brzucha",),
        secondary=("mięśnie skośne",),
        equipment=("mata/ławka",),
        level="początkujący", kind="izolowane",
        pattern="tyłopochylenie miednicy",
        tags=("brzuch i mięśnie głębokie", "tyłopochylenie miednicy", "izolowane"),
        benefit="tulow", steps="ogolny",
        breathing="plynnie", mistakes="ogolne",
        easier="ogolna", harder="ogolna",
    ),
    LibraryRow(
        "EX-CORE-006", "Naprzemienne opuszczanie kończyn w leżeniu",
        "Dead Bug",
        "Brzuch i mięśnie głębokie",
        primary=("mięśnie głębokie tułowia",),
        secondary=("prosty brzucha", "zginacze biodra"),
        equipment=("mata",),
        level="początkujący", kind="stabilizacyjne",
        pattern="antywyprost",
        tags=("brzuch i mięśnie głębokie", "antywyprost", "stabilizacyjne"),
        benefit="tulow", steps="stabilizacja",
        breathing="plynnie", mistakes="ogolne",
        easier="dzwignia", harder="ogolna",
    ),
    LibraryRow(
        "EX-CORE-007", "Deska przodem",
        "Plank",
        "Brzuch i mięśnie głębokie",
        primary=("mięśnie głębokie tułowia",),
        secondary=("prosty brzucha", "pośladki", "obręcz barkowa"),
        equipment=("mata",),
        level="początkujący", kind="stabilizacyjne",
        pattern="antywyprost",
        tags=("brzuch i mięśnie głębokie", "antywyprost", "stabilizacyjne"),
        benefit="tulow", steps="stabilizacja",
        breathing="plynnie", mistakes="ogolne",
        easier="dzwignia", harder="ogolna",
    ),
    LibraryRow(
        "EX-CORE-008", "Deska bokiem",
        "Side Plank",
        "Brzuch i mięśnie głębokie",
        primary=("mięśnie skośne brzucha", "czworoboczny lędźwi"),
        secondary=("pośladkowy średni", "obręcz barkowa"),
        equipment=("mata",),
        level="początkujący/średniozaawansowany", kind="stabilizacyjne",
        pattern="antyzgięcie boczne",
        tags=("brzuch i mięśnie głębokie", "antyzgięcie boczne", "stabilizacyjne"),
        benefit="tulow", steps="stabilizacja",
        breathing="plynnie", mistakes="ogolne",
        easier="dzwignia", harder="ogolna",
    ),
    LibraryRow(
        "EX-CORE-009", "Wyciskanie antyrotacyjne na wyciągu",
        "Pallof Press",
        "Brzuch i mięśnie głębokie",
        primary=("mięśnie głębokie tułowia", "skośne brzucha"),
        secondary=("pośladki", "obręcz barkowa"),
        equipment=("wyciąg/guma",),
        level="początkujący", kind="stabilizacyjne",
        pattern="antyrotacja",
        tags=("brzuch i mięśnie głębokie", "antyrotacja", "stabilizacyjne"),
        benefit="tulow", steps="stabilizacja",
        breathing="plynnie", mistakes="ogolne",
        easier="dzwignia", harder="ogolna",
    ),
    LibraryRow(
        "EX-CORE-010", "Spacer z ciężarem po jednej stronie",
        "Suitcase Carry",
        "Brzuch i mięśnie głębokie",
        primary=("mięśnie skośne", "czworoboczny lędźwi", "core"),
        secondary=("chwyt", "pośladki", "obręcz barkowa"),
        equipment=("hantel/kettlebell",),
        level="średniozaawansowany", kind="wielostawowe",
        pattern="antyzgięcie boczne/chód",
        tags=("brzuch i mięśnie głębokie", "antyzgięcie boczne/chód", "wielostawowe"),
        benefit="tulow", steps="stabilizacja",
        breathing="plynnie", mistakes="ogolne",
        easier="dzwignia", harder="ogolna",
    ),
    # --- Przedramiona i chwyt ---
    LibraryRow(
        "EX-CHWYT-001", "Spacer farmera",
        "Farmer's Walk",
        "Przedramiona i chwyt",
        primary=("mięśnie chwytu i przedramion",),
        secondary=("mięsień czworoboczny", "core", "nogi"),
        equipment=("hantle/kettlebell",),
        level="początkujący/średniozaawansowany", kind="wielostawowe",
        pattern="przenoszenie ciężaru",
        tags=("przedramiona i chwyt", "przenoszenie ciężaru", "wielostawowe"),
        benefit="chwyt", steps="chwyt",
        breathing="plynnie", mistakes="ogolne",
        easier="ogolna", harder="ogolna",
    ),
    LibraryRow(
        "EX-CHWYT-002", "Zwis na drążku",
        "Dead Hang",
        "Przedramiona i chwyt",
        primary=("mięśnie chwytu i przedramion",),
        secondary=("mięśnie obręczy barkowej",),
        equipment=("drążek",),
        level="początkujący", kind="izometryczne",
        pattern="chwyt izometryczny",
        tags=("przedramiona i chwyt", "chwyt izometryczny", "izometryczne"),
        benefit="chwyt", steps="chwyt",
        breathing="plynnie", mistakes="ogolne",
        easier="ogolna", harder="ogolna",
    ),
    LibraryRow(
        "EX-CHWYT-003", "Zwis na ręcznikach",
        "Towel Hang",
        "Przedramiona i chwyt",
        primary=("mięśnie chwytu i palców",),
        secondary=("przedramiona", "obręcz barkowa"),
        equipment=("drążek", "ręczniki"),
        level="zaawansowany", kind="izometryczne",
        pattern="chwyt izometryczny",
        tags=("przedramiona i chwyt", "chwyt izometryczny", "izometryczne"),
        benefit="chwyt", steps="chwyt",
        breathing="plynnie", mistakes="ogolne",
        easier="ogolna", harder="ogolna",
    ),
    LibraryRow(
        "EX-CHWYT-004", "Trzymanie talerzy palcami",
        "Plate Pinch",
        "Przedramiona i chwyt",
        primary=("mięśnie chwytu", "kciuk"),
        secondary=("przedramiona",),
        equipment=("talerze obciążeniowe",),
        level="średniozaawansowany", kind="izometryczne",
        pattern="chwyt szczypcowy",
        tags=("przedramiona i chwyt", "chwyt szczypcowy", "izometryczne"),
        benefit="chwyt", steps="chwyt",
        breathing="plynnie", mistakes="ogolne",
        easier="ogolna", harder="ogolna",
    ),
    LibraryRow(
        "EX-CHWYT-005", "Uginanie nadgarstków podchwytem",
        "Wrist Curl",
        "Przedramiona i chwyt",
        primary=("zginacze nadgarstka",),
        secondary=("zginacze palców",),
        equipment=("hantle/sztanga",),
        level="początkujący", kind="izolowane",
        pattern="zgięcie nadgarstka",
        tags=("przedramiona i chwyt", "zgięcie nadgarstka", "izolowane"),
        benefit="chwyt", steps="ogolny",
        breathing="plynnie", mistakes="ogolne",
        easier="ogolna", harder="ogolna",
    ),
    LibraryRow(
        "EX-CHWYT-006", "Prostowanie nadgarstków nachwytem",
        "Reverse Wrist Curl",
        "Przedramiona i chwyt",
        primary=("prostowniki nadgarstka",),
        secondary=("prostowniki palców",),
        equipment=("hantle/sztanga",),
        level="początkujący", kind="izolowane",
        pattern="wyprost nadgarstka",
        tags=("przedramiona i chwyt", "wyprost nadgarstka", "izolowane"),
        benefit="chwyt", steps="ogolny",
        breathing="plynnie", mistakes="ogolne",
        easier="ogolna", harder="ogolna",
    ),
    LibraryRow(
        "EX-CHWYT-007", "Uginanie ramion nachwytem",
        "Reverse Curl",
        "Przedramiona i chwyt",
        primary=("mięsień ramienno-promieniowy",),
        secondary=("mięsień ramienny", "biceps", "prostowniki nadgarstka"),
        equipment=("sztanga EZ/prosta",),
        level="początkujący/średniozaawansowany", kind="izolowane",
        pattern="zgięcie łokcia",
        tags=("przedramiona i chwyt", "zgięcie łokcia", "izolowane"),
        benefit="chwyt", steps="zgiecie_lokcia",
        breathing="plynnie", mistakes="ogolne",
        easier="ogolna", harder="ogolna",
    ),
    LibraryRow(
        "EX-CHWYT-008", "Nawijanie ciężaru na wałek",
        "Wrist Roller",
        "Przedramiona i chwyt",
        primary=("zginacze i prostowniki przedramion",),
        secondary=("chwyt",),
        equipment=("wałek do nadgarstków",),
        level="średniozaawansowany", kind="izolowane",
        pattern="zgięcie/wyprost nadgarstka",
        tags=("przedramiona i chwyt", "zgięcie/wyprost nadgarstka", "izolowane"),
        benefit="chwyt", steps="ogolny",
        breathing="plynnie", mistakes="ogolne",
        easier="ogolna", harder="ogolna",
    ),
    LibraryRow(
        "EX-CHWYT-009", "Nawracanie i odwracanie przedramienia z hantlem",
        "Dumbbell Pronation/Supination",
        "Przedramiona i chwyt",
        primary=("nawracacze i odwracacze przedramienia",),
        secondary=("mięśnie chwytu",),
        equipment=("lekki hantel/młotek treningowy",),
        level="początkujący", kind="izolowane",
        pattern="pronacja/supinacja",
        tags=("przedramiona i chwyt", "pronacja/supinacja", "izolowane"),
        benefit="chwyt", steps="ogolny",
        breathing="plynnie", mistakes="ogolne",
        easier="ogolna", harder="ogolna",
    ),
    LibraryRow(
        "EX-CHWYT-010", "Ściskanie ściskacza dłoni",
        "Hand Gripper",
        "Przedramiona i chwyt",
        primary=("zginacze palców", "mięśnie chwytu"),
        secondary=("przedramiona",),
        equipment=("ściskacz dłoni",),
        level="początkujący/średniozaawansowany", kind="izolowane",
        pattern="zaciskanie dłoni",
        tags=("przedramiona i chwyt", "zaciskanie dłoni", "izolowane"),
        benefit="chwyt", steps="ogolny",
        breathing="plynnie", mistakes="ogolne",
        easier="ogolna", harder="ogolna",
    ),
]

def _assert_rows() -> None:
    """Kontrakt danych: żaden wiersz nie ma prawa wskazać nieistniejącego
    szablonu ani powtórzyć identyfikatora. Sprawdzane przy imporcie modułu
    i osobnym testem — literówka w kluczu ma się wysypać od razu."""
    seen: set[str] = set()
    for row in LIBRARY_ROWS:
        if row.id in seen:
            raise RuntimeError(f"Powtórzony identyfikator biblioteki: {row.id}")
        seen.add(row.id)
        for value, table, label in (
            (row.steps, STEP_TEXTS, "kroków"),
            (row.breathing, BREATHING_TEXTS, "oddychania"),
            (row.mistakes, MISTAKE_TEXTS, "błędów"),
            (row.benefit, BENEFIT_TEXTS, "zastosowania"),
            (row.easier, EASIER_TEXTS, "regresji"),
            (row.harder, HARDER_TEXTS, "progresji"),
        ):
            if value not in table:
                raise RuntimeError(
                    f"{row.id}: nieznany szablon {label}: {value!r}"
                )


_assert_rows()
